module.exports = {
	symbols:[ 
        {script: '\\pm', img:'images/binary/pm.png'},
        {script: '\\mp', img:'images/binary/mp.png'},
        {script: '\\times', img:'images/binary/times.png'},
        {script: '\\div', img:'images/binary/div.png'},
        {script: '\\ast', img:'images/binary/ast.png'},
        {script: '\\star', img:'images/binary/star.png'},
        {script: '\\dagger', img:'images/binary/dagger.png'},
        {script: '\\ddagger', img:'images/binary/ddagger.png'},
        {script: '\\cap', img:'images/binary/cap.png'},
        {script: '\\cup', img:'images/binary/cup.png'},
        {script: '\\uplus', img:'images/binary/uplus.png'},
        {script: '\\sqcap', img:'images/binary/sqcap.png'},
        {script: '\\sqcup', img:'images/binary/sqcup.png'},
        {script: '\\vee', img:'images/binary/vee.png'},
        {script: '\\wedge', img:'images/binary/wedge.png'},
        {script: '\\cdot', img:'images/binary/cdot.png'},
        {script: '\\diamond', img:'images/binary/diamond.png'},
        {script: '\\bigtriangleup', img:'images/binary/bigtriangleup.png'},
        {script: '\\bigtriangledow', img:'images/binary/bigtriangledown.png'},
        {script: '\\triangleleft', img:'images/binary/triangleleft.png'},
        {script: '\\triangleright', img:'images/binary/triangleright.png'},
        {script: '\\bigcirc', img:'images/binary/bigcirc.png'},
        {script: '\\bullet', img:'images/binary/bullet.png'},
        {script: '\\wr', img:'images/binary/wr.png'},
        {script: '\\oplus', img:'images/binary/oplus.png'},
        {script: '\\ominus', img:'images/binary/ominus.png'},
        {script: '\\otimes', img:'images/binary/otimes.png'},
        {script: '\\oslash', img:'images/binary/oslash.png'},
        {script: '\\odot', img:'images/binary/odot.png'},
        {script: '\\circ', img:'images/binary/circ.png'},
        {script: '\\setminus', img:'images/binary/setminus.png'},
        {script: '\\amalg', img:'images/binary/amalg.png'}           

      ]
};