module.exports = {
	symbols:[ {script: '<', img:'images/symbols/menor.png'},
        {script:'\\leq ', img:'images/symbols/leq.png'},
        {script:'\\ll',img:'images/symbols/ll.png'},
        {script:'\\subset',img:'images/symbols/subset.png'},
        {script:'\\subseteq',img:'images/symbols/subseteq.png'},
        {script:'\\nsubseteq',img:'images/symbols/nsubseteq.png'},
        {script:'\\sqsubset',img:'images/symbols/sqsubset.png'},
        {script:'\\sqsubseteq',img:'images/symbols/sqsubseteq.png'},
        {script:'\\preceq',img:'images/symbols/preceq.png'},
        {script:'>',img:'images/symbols/mayor.png'},
        {script:'\\geq',img:'images/symbols/geq.png'},
        {script:'\\gg',img:'images/symbols/gg.png'},
        {script:'\\supset',img:'images/symbols/supset.png'},
        {script:'\\supseteq',img:'images/symbols/supseteq.png'},
        {script:'\\nsupseteq',img:'images/symbols/nsupseteq.png'},
        {script:'\\sqsupset',img:'images/symbols/sqsupset.png'},
        {script:'\\sqsupseteq',img:'images/symbols/sqsupseteq.png'},
        {script:'\\succeq',img:'images/symbols/succeq.png'},
        {script:'=',img:'images/symbols/igual.png'},
        {script:'\\doteq',img:'images/symbols/doteq.png'},
        {script:'\\equiv',img:'images/symbols/equiv.png'},
        {script:'\\approx',img:'images/symbols/approx.png'},
        {script:'\\cong',img:'images/symbols/cong.png'},
        {script:'\\simeq',img:'images/symbols/simeq.png'},
        {script:'\\sim',img:'images/symbols/sim.png'},
        {script:'\\propto',img:'images/symbols/propto.png'},
        {script:'\\neq',img:'images/symbols/neq.png'}
      ]
};